# Generated by Django 6.0.2 on 2026-03-12 22:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('service_type', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_service', 'In Service'), ('no_show', 'No Show'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('estimated_wait', models.PositiveIntegerField(blank=True, help_text='Estimated wait in minutes', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'db_table': 'waitlist_entry',
                'ordering': ['priority', 'position'],
                'abstract': False,
                'indexes': [models.Index(fields=['hub_id', 'status'], name='waitlist_en_hub_id_c537ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaitlistSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('average_service_time', models.PositiveIntegerField(default=30, help_text='Average service time in minutes')),
                ('max_queue_size', models.PositiveIntegerField(default=20, help_text='Maximum number of entries in the queue')),
                ('display_mode', models.BooleanField(default=False, help_text='Enable public display mode')),
            ],
            options={
                'verbose_name': 'Waitlist Settings',
                'verbose_name_plural': 'Waitlist Settings',
                'db_table': 'waitlist_settings',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('hub_id',), name='unique_waitlist_settings_per_hub')],
            },
        ),
    ]
